name: Build Push Deploy to OKE

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image Tag"
        required: true
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # -------------------------
    # Checkout
    # -------------------------
    - name: Checkout Code
      uses: actions/checkout@v4

    # -------------------------
    # Install OCI CLI
    # -------------------------
    - name: Install OCI CLI
      run: |
        bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" --accept-all-defaults
        echo "$HOME/bin" >> $GITHUB_PATH
        export PATH=$HOME/bin:$PATH
        oci --version

    # -------------------------
    # Configure OCI CLI
    # -------------------------
    - name: Configure OCI CLI
      run: |
        mkdir -p ~/.oci

        cat > ~/.oci/config <<EOF
[DEFAULT]
user=${{ secrets.OCI_USER_OCID }}
fingerprint=${{ secrets.OCI_FINGERPRINT }}
tenancy=${{ secrets.OCI_TENANCY_OCID }}
region=${{ secrets.OCI_REGION }}
key_content=${{ secrets.OCI_KEY_CONTENT }}
EOF

    # -------------------------
    # Generate kubeconfig (OKE)
    # -------------------------
    - name: Generate kubeconfig
      run: |
        mkdir -p $HOME/.kube

        oci ce cluster create-kubeconfig \
          --cluster-id ${{ secrets.OKE_CLUSTER_ID }} \
          --file $HOME/.kube/config \
          --region ${{ secrets.OCI_REGION }} \
          --token-version 2.0.0 \
          --kube-endpoint PUBLIC_ENDPOINT

    # -------------------------
    # Test cluster access
    # -------------------------
    - name: Test OKE
      run: |
        kubectl version --client
        kubectl get nodes
        kubectl get ns
