name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image name (lowercase safe)
        run: |
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}/train1-app:latest" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Push Docker image
        run: docker push $IMAGE