name: Build and Push to OCIR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to OCIR
        run: |
          echo "${{ secrets.OCIR_AUTH_TOKEN }}" | docker login ${{ secrets.OCIR_REGISTRY }} \
          -u "${{ secrets.OCIR_USERNAME }}" \
          --password-stdin

      - name: Build image
        run: |
          docker build \
            -t sin.ocir.io/axrbgxv6g86f/dev_repo:${{ github.run_number }} \
            -t sin.ocir.io/axrbgxv6g86f/dev_repo:latest .

      - name: Push build-number tag
        run: |
          docker push sin.ocir.io/axrbgxv6g86f/dev_repo:${{ github.run_number }}

      - name: Push latest tag
        run: |
          docker push sin.ocir.io/axrbgxv6g86f/dev_repo:latest

      - name: Show image version
        run: |
          echo "Published image: sin.ocir.io/axrbgxv6g86f/dev_repo:${{ github.run_number }}"